security:
    encoders:
        Crm\MainBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_DRIVER: [ROLE_USER]
        ROLE_COMPANY: [ROLE_USER]
        ROLE_ADMIN: [ROLE_DRIVER, ROLE_COMPNAY]

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    providers:
        main:
            entity: { class: CrmMainBundle:User, property: username }
    firewalls:
        main:
            pattern: /.*
            form_login:
                check_path: /login_check
                login_path: /login
            logout: true
            security: true
            anonymous: true

#    access_control:
#        - { path: /admin, role: ROLE_ADMIN }