security:
    encoders:
        Crm\MainBundle\Entity\Operator:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

#    role_hierarchy:
#        ROLE_DRIVER:  [ROLE_USER]
#        ROLE_COMPANY: [ROLE_USER]
#        ROLE_ADMIN:   [ROLE_DRIVER, ROLE_COMPANY]

#    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    providers:
        operator:
            entity: { class: CrmMainBundle:Operator, property: username }
    firewalls:
        operator:
            pattern: /operator
            form_login:
                check_path: /operator/login_check
                login_path: /operator/login
                default_target_path: /operator/activate-list
            logout: true
            security: true
            anonymous: true


    access_control:
#        - { path: /operator/.*, role: ROLE_OPERATOR }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }